name=BlynkEdgent
version=1.0.0
author=Blynk
license=Apache-2.0
maintainer=Volodymyr Shymanskyy <vshymanskyi@gmail.com>
sentence=Blynk.Edgent for Arduino IDE.
paragraph=WiFi provisioning (using BLE or WiFi-AP), secure Blynk.Cloud connectivity and OTA updates out of the box. Works with ESP32 and ESP8266 boards.
category=Communication
url=https://blynk.io
architectures=esp32,esp8266
includes=BlynkEdgent.h
depends=Blynk,ArduinoJson,ArduinoHttpClient,NimBLE-Arduino
